# Generated by Django 3.2.8 on 2024-07-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_category',
            field=models.CharField(blank=True, choices=[], max_length=50),
        ),
    ]
