# Generated by Django 3.2.8 on 2024-07-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_project_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sub_category',
        ),
    ]
