# Generated by Django 3.2.8 on 2024-07-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_remove_project_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
