# Generated by Django 3.2.8 on 2024-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_project_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('photo', models.ImageField(upload_to='resume/photo/')),
            ],
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='ProjectImage/'),
        ),
    ]
