# Generated by Django 3.2.8 on 2024-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20240715_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrerdetail',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
